### ISSUE TITLE
Crash on page refresh after hot reload

### ISSUE THREAD

**Issue by alexander-entin** [rakkasjs/rakkasjs#123]
````shell
yarn create rakkas-app -y rakkas
cd rakkas
yarn dev
````
open `http://localhost:5173/`
edit `src/routes/index.page.tsx`
refresh the page
````
Uncaught Error: Cannot read properties of undefined (reading 'add')
    at updateDehydratedSuspenseComponent (react-dom.development.js:20662:17)
    at updateSuspenseComponent (react-dom.development.js:20362:16)
    at beginWork (react-dom.development.js:21624:14)
    at beginWork$1 (react-dom.development.js:27426:14)
    at performUnitOfWork (react-dom.development.js:26557:12)
    at workLoopSync (react-dom.development.js:26466:5)
    at renderRootSync (react-dom.development.js:26434:7)
    at performConcurrentWorkOnRoot (react-dom.development.js:25738:74)
    at workLoop (scheduler.development.js:266:34)
    at flushWork (scheduler.development.js:239:14)
````
````
TypeError: Cannot read properties of undefined (reading 'add')
    at r2.init (C:/work/rakkas/node_modules/rakkasjs/dist/server.js:1707:80)
    at r2.render (C:/work/rakkas/node_modules/rakkasjs/dist/server.js:1709:17)
    at finishClassComponent (C:\work\rakkas\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5663:31)
    at renderClassComponent (C:\work\rakkas\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5696:3)
    at renderElement (C:\work\rakkas\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5943:7)
    at renderNodeDestructiveImpl (C:\work\rakkas\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (C:\work\rakkas\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderContextConsumer (C:\work\rakkas\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5906:3)
    at renderElement (C:\work\rakkas\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6023:11)
    at renderNodeDestructiveImpl (C:\work\rakkas\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (C:\work\rakkas\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at finishClassComponent (C:\work\rakkas\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5688:3)
    at renderClassComponent (C:\work\rakkas\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5696:3)
    at renderElement (C:\work\rakkas\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5943:7)
    at renderNodeDestructiveImpl (C:\work\rakkas\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (C:\work\rakkas\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (C:\work\rakkas\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5785:7)
    at renderElement (C:\work\rakkas\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (C:\work\rakkas\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (C:\work\rakkas\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderNode (C:\work\rakkas\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (C:\work\rakkas\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (C:\work\rakkas\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (C:\work\rakkas\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderElement (C:\work\rakkas\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5971:9)
    at renderNodeDestructiveImpl (C:\work\rakkas\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (C:\work\rakkas\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (C:\work\rakkas\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5785:7)
    at renderElement (C:\work\rakkas\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (C:\work\rakkas\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (C:\work\rakkas\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (C:\work\rakkas\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5785:7)
    at renderElement (C:\work\rakkas\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (C:\work\rakkas\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (C:\work\rakkas\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at retryTask (C:\work\rakkas\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6528:5)
    at performWork (C:\work\rakkas\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6576:7)
    at C:\work\rakkas\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5382:14
    at scheduleWork (C:\work\rakkas\node_modules\react-dom\cjs\react-dom-server.browser.development.js:77:3)
    at pingTask (C:\work\rakkas\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5381:5)
    at ping (C:\work\rakkas\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5413:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
````

**Comment by cyco130** [comment]
This is fixed i `rakkasjs@next` but unfortunately it's not easily back-portable to the stable version (0.6). Upgrading to `0.7.0-next.11` should solve your problem. It will be released as the next stable soon anyway.
