### ISSUE TITLE
Bug: `emotion` example does not work

### ISSUE THREAD

**Issue by tkamenoko** [rakkasjs/rakkasjs#41]
Building production server of `emotion` example with prerendering throws an error.

* OS: Windiows11, Ubuntu 20.04
* Nodejs: v16.16.0

Vite config:
```ts
// examples/emotion/vite.config.ts
import { defineConfig } from "vite";
import rakkas from "rakkasjs/vite-plugin";

export default defineConfig({
	plugins: [
		rakkas({
			prerender: true,
			react: {
				jsxImportSource: "/src/emotion",
				babel: {
					plugins: ["@emotion/babel-plugin"],
				},
			},
		}),
	],
});

```

Running commands:
```
pnpm run build
pnpm run --filter ./examples/emotion build
```

Output:
```
rakkas: Building client (1/3)
vite v3.0.4 building for production...
✓ 65 modules transformed.
dist/client/manifest.json                   0.42 KiB
dist/client/assets/index.page.f0680709.js   6.48 KiB / gzip: 3.19 KiB
dist/client/assets/index.bdd9e053.js        188.43 KiB / gzip: 62.10 KiB

rakkas: Building server (2/3)
vite v3.0.4 building SSR bundle for production...
✓ 22 modules transformed.
dist/server/index.js                                                       19.07 KiB
dist/server/hattip.js                                                      113.95 KiB
dist/server/assets/entry-node.default.59c91c71.js                          214.05 KiB
dist/server/assets/virtual_rakkasjs_api-routes.0a71bd76.js                 0.09 KiB
dist/server/assets/virtual_rakkasjs_server-page-routes.b14e942a.js         0.22 KiB
dist/server/assets/virtual_rakkasjs_run-server-side_manifest.7c34ad2e.js   0.11 KiB
dist/server/assets/index.page.4afbec9f.js                                  2.92 KiB
dist/server/assets/multipart-parser.f227c092.js                            9.99 KiB

rakkas: Prerendering static routes (3/3)
TypeError: _styled is not a function
    at file:///C:/Users/tkamemnoko/dev/rakkasjs/examples/emotion/dist/server/assets/index.page.4afbec9f.js:6:41
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async Promise.all (index 0)
    at async renderPageRoute (file:///C:/Users/tkamemnoko/dev/rakkasjs/examples/emotion/dist/server/hattip.js:2697:19)    
    at async hooks.map._a (file:///C:/Users/tkamemnoko/dev/rakkasjs/examples/emotion/dist/server/hattip.js:3218:14)       
    at async file:///C:/Users/tkamemnoko/dev/rakkasjs/examples/emotion/dist/server/hattip.js:259:16
    at async file:///C:/Users/tkamemnoko/dev/rakkasjs/examples/emotion/dist/server/hattip.js:235:22
    at async prerender (file:///C:/Users/tkamemnoko/dev/rakkasjs/examples/emotion/dist/server/hattip.js:3241:20)
✓ 1 static routes prerendered.
404 dist/client/index.html
```

**Comment by cyco130** [comment]
Thanks for reporting. It's one of those ESM/CJS issues again. Quickest fix is to add `ssr: { noExternal: ["@emotion/styled"] }` to the Vite config. I'll have a better look at it but it needs to be solved in Emotion really :(

**Comment by cyco130** [comment]
The workaround above works, so closing this.
